#!/usr/bin/python3
import sys

# Read the input file
filename = sys.argv[1]
with open(filename, 'r') as file:
    numbers = file.read().splitlines()

# Factorize the numbers
for number in numbers:
    number = int(number)
    factors = []
    i = 2
    while i * i <= number:
        if number % i == 0:
            factors.append((i, number // i))
            number //= i

        else:
            i += 1

    if number > 1:
        factors.append((number, 1))
        # Print the factoriation
        for factor in factors:
            print(f"{number}={factor[0]}*{factor[1]}")
